{{- if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deploymentName }}-env
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}
